Fixed Platformios Click crashing within Bazel
mum4k/platformio_rules pull request #23
Opened 2020-03-13 19:02 UTC by kkevlar

Fixes bug as described in #22.

Not sure how widespread this bug is for users, but I need this fix in order to use the extension.

2020-03-13 20:35 UTC, mum4k requested changes

2020-03-13 20:35 UTC, mum4k commented on platformio/platformio.bzl
> +        "LC_ALL":"C.UTF-8",
Would you mind adding a comment above these new envs explaining why we need them and maybe including a link to the bug?

2020-03-15 18:33 UTC, kkevlar reviewed
Added this comment

2020-03-15 18:35 UTC, mum4k approved these changes
Thank you.

2020-03-15 18:36 UTC, merged